backend:
  name: git-gateway
  branch: main
media_folder: "_site/images/uploads"
public_folder: "/images/uploads" 

collections:
  - name: "Article Posts"
    tags: "posts"
    label: "Article Posts"
    folder: "src/posts/blog posts"
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "layout", name: "layout", widget: "hidden", default: "layouts/post.html"}
      - {label: "tags", name: "tags", widget: "hidden", default: "posts"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image ", name: "featuredImage", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Post Body", name: "body", widget: "markdown"}
  - name: "About Me Section"
    tags: "About Me"
    label: "About Me Section"
    folder: "src/posts/aboutMeSection"
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "layout", name: "layout", widget: "hidden", default: "layouts/post.html"}
      - {label: "tags", name: "tags", widget: "hidden", default: "about"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Featured Image ", name: "featuredImage", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Post Body", name: "body", widget: "markdown"}